server:
  port: 9090

spring:
  application:
    name: API-GATEWAY
  config:
    import: configserver:http://localhost:9296
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id : ORDER-SERVICE
          uri: lb://ORDER-SERVICE
          predicates:
            - Path=/order/**
          filters:
            - name: CircuitBreaker
              args:
                name: ORDER-SERVICE
                fallbackuri: forward:/orderServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PAYMENT-SERVICE
          uri: lb://PAYMENT-SERVICE
          predicates:
            - Path=/payment/**
          filters:
            - name: CircuitBreaker
              args:
                name: PAYMENT-SERVICE
                fallbackuri: forward:/paymentServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
        - id: PRODUCT-SERVICE
          uri: lb://PRODUCT-SERVICE
          predicates:
            - Path=/product/**
          filters:
            - name: CircuitBreaker
              args:
                name: PRODUCT-SERVICE
                fallbackuri: forward:/productServiceFallBack
            - name: RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 1
                redis-rate-limiter.burstCapacity: 1
  security:
    oauth2:
      client:
        registration:
          auth0:
            client-id: oJxE4FWOAudT8DopBSkkbGJlDafjZutTr
            client-secret: o5qGixS8iFsFK4vZHGCc0IBqrKiQppKa58YbTJg9kVnnfq01UrVmjMkpvz6nOqj
            scope: openid, email, profile, offline_access, Customer, Admin
            authorization-grant-type: authorization_code  # ✅ Ensure it's `authorization_code`
            redirect-uri: "{baseUrl}/login/oauth2/code/auth0"
            #client-authentication-method: client_secret_basic
        provider:
          auth0:
            issuer-uri: https://dev-x3146s2bsfpgsu1q.us.auth0.com/
            jwk-set-uri: https://dev-x3146s2bsfpgsu1q.us.auth0.com/.well-known/jwks.json
      resourceserver:
        jwt:
          issuer-uri: https://dev-x3146s2bsfpgsu1q.us.auth0.com/

auth0:
  audience: https://dev-x3146s2bsfpgsu1q.us.auth0.com/api/v2/



logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
